language: rust
sudo: false
cache: cargo
rust:
  - nightly-2018-04-19
  - beta
  - stable

env:
  global:
    - CLIPPY_VERSION=0.0.195
    - secure: "AP4j/9f8iOaV5gETQYp1X74OwC919nP1wwZMr0soDJ76xxYzEVsAGm+B1QBpmxasYch/ylUe1F0xM7uTxnZg4zMV7Wx4f62V7OW2AA7hZaIoLutzN73SErqPj6wCWbrp26gZbSW/xKKysIKZLFfADXxXQcDqk/INOPK97URrcQIyIRtYTMDCqHUjCxloiN008G2Rht+adJ3CK0c9H5huvq5Ku6FVtG22FssQUEI0Bl3lk4v6M8MuSUMOcf0Cjr7VK2L1sWDjhUvQlh3M1BrYZox89JlNXqYDgagyNr9so/5KxSA1jnaHLZU9v6r5T8rRH2liL/cRt9rGdxxjdjmFnTVylzWFzej7HkM/p3C3F8ZW7OS/PHS0/BnqGLr5A6IWMTfGfxCMg9Z3UOazk6E/RPB+V79oDmFi40I06fNFWPxth34ytJ2r5Kjd9aAAN/DkhTFor7KQ6xdS7keOx9sml4f6DrN/SI6hEsrQlZPcGKRjD2EsPksdLjXTZ8DSJ3HbMF8+edK4AYMvygJBC8BxI/wY2bTA3Iy7pUvH/teZOmcPKWiD9tist6jo+iaPUNFCRTYD4a74r6R4rMgaN6w6m5wnoslsqwqrl86zgn++V5rcNu7j3ffn5gVcsvDfQTQpuvgACjwAejjKHcgL+tCq09JrvLgsmxfBif0Hlb3MQg4="

before_script:
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo install clippy --vers $CLIPPY_VERSION --force;
    esac

script:
  - cargo test
  - cargo test --no-default-features
  - cargo test --all-features
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo clippy -- -D warnings;
      cargo clippy --no-default-features -- -D warnings;
      cargo clippy --all-features -- -D warnings;
    esac

before_deploy:
  - cargo package

deploy:
  provider: script
  script: cargo publish --verbose --token "$CRATES_IO_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
